### PR TITLE
Add lerna and split project

### PR DESCRIPTION
**Pull request by nlepage**
### Description
 - [x] Add lerna and move sources in a package
 - [x] Move scripts in top level package.json
 - [x] Split the project
 - [x] Fix all... (documentation, tests, lint, coverage, ci)

**Issue :** #78

### CODE REVIEW

**Comment by nlepage** [comment]
Codecov seems pretty lost... 
Last execution reported an error : https://codecov.io/github/Zenika/immutadot/commit/fb0dfc641e0302057f34707bc358bc44f236b765
Either the report is empty, or it fails to find source files...

**Comment by nlepage** [comment]
`yarn test` crashes in `immutadot-lodash`
Module resolver can't find imports relative to `immutadot/src`...

**Comment by nlepage** [comment]
OK for some reason I had removed module-resolver from babel's build (when making flow), and this was a huge mistake.
I put it back, and it fixed immutadot-lodash's tests.

It made me realise that immutadot-lodash's tests rely on the built immutadot core.
So it's necessary to execute `yarn build` on immutadot core before executing immutadot-lodash's tests for these to work...

**Comment by nlepage** [comment]
Codecov is back on his feet, but it reports -45 files so it is missing one of the reports...

**Comment by nlepage** [comment]
Maybe tests should be rewritten to real unit tests, so that these don't rely on immutadot's core...

**Comment by nlepage** [comment]
Finally codecov is OK. But codecov ignores wouldn't work, I had to use jest ignores. And codecov flags still aren't working...

**Comment by frinyvonnick** [comment]
When i execute `yarn`to install dependencies i have the following warning: 
```
warning "workspace-aggregator-d2639e58-f6c2-4c62-a6fd-4cb79bd5a18f > immutadot@0.3.2" has unmet peer dependency "lodash@^4.17.4".
```
Then when i execute `yarn test` i have a bunch of errors like:
```
FAIL packages/immutadot-lodash/src/string/capitalize.spec.js
  ● Test suite failed to run

    Cannot find module 'immutadot/core/convert' from 'capitalize.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous>.Object.defineProperty.value (packages/immutadot-lodash/src/string/capitalize.js:1:335)
      at Object.<anonymous> (packages/immutadot-lodash/src/string/capitalize.js:1:495)
```

**Comment by frinyvonnick** [comment]
Maybe we could had a `pretest`for this to be transparent for developper ?

**Comment by nlepage** [comment]
As I mentionned in https://github.com/Zenika/immutadot/pull/138#issuecomment-345346921 I find it a little overkill, and I'm not sure if it's possible to have inter-package script dependency...

**Comment by nlepage** [comment]
@frinyvonnick I added immutadot's build to immutadot-lodash's pretest, this is ready for review.

**Comment by frinyvonnick** [comment]
Nice work :+1:

**Pull request merged**
